name: Deploy application

on:
  push:
    branches:
      - '**'
    paths:
      - "main.py"
      - "templates/**"
      - "static/**"
      - "Dockerfile"
      - "requirements.txt"
      - "docker-compose.yml"
      - ".github/workflows/cd.yml"


      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: |
          cd terraform
          terraform init

      - name: Terraform apply
        run: |
          cd terraform
          terraform apply -auto-approve -var="branch_name=${GITHUB_REF_NAME}"
          
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Flask-Todo-List
            echo "IMAGE_TAG=${{ github.sha }}" > image.env
            sudo docker compose --env-file image.env pull web
            sudo docker compose --env-file image.env up -d web
            sudo docker image prune -f