name: Deploy application

on:
  push:
    branches:
      - '**'
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
            
      - name: Write SSH public key for Terraform
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PUBLIC_KEY }}" > ~/.ssh/flask-todo-key.pub
          chmod 600 ~/.ssh/flask-todo-key.pub

      - name: Terraform init
        run: |
          cd terraform
          terraform init

      - name: Terraform apply
        run: |
          cd terraform
          terraform apply -auto-approve \
            -var="branch_name=${GITHUB_REF_NAME}" \
            -var="public_key_path=/home/runner/.ssh/flask-todo-key.pub" \
            -var="allowed_ssh_cidr=0.0.0.0/0"
      
      - name: Get EC2 public IP
        run: |
          cd terraform
          echo "PUBLIC_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Flask-Todo-List
            echo "IMAGE_TAG=${{ github.sha }}" > image.env
            sudo docker compose --env-file image.env pull web
            sudo docker compose --env-file image.env up -d web
            sudo docker image prune -f